### ISSUE TITLE
FATAL EXCEPTION: main java.lang.NoClassDefFoundError: android.support.v7.internal.widget.TintManager

### ISSUE THREAD

**Issue by freesbe** [Swrve/swrve-android-sdk#126]
Because of dynamic dependency:
`com.android.support:appcompat-v7:23.+`

After new version of support libraries has been released and someone is still using older version of `appcompat` and lets say `design` he can face this issue.

All support libraries has to come with the same version number.

As adviced by `Dan Lew`:
http://blog.danlew.net/2015/09/09/dont-use-dynamic-versions-for-your-dependencies/

The best option will be to use `provided` scope for the support libraries.

**Comment by Sergio-Mira** [comment]
Thanks @freesbe we'll specify the version we are using, will be able to be overwritten by defining a dependency in the app itself

**Comment by rowest** [comment]
Same problem in my app, I'm using com.android.support:appcompat-v7:23.1.0 and can't update it to 23.4.0 for some reason. How can I use your lib in this case?

**Comment by Sergio-Mira** [comment]
If you include the same version for the 'v4' library in your app too does it solve your issues? We are going to specify the version we use (23.3.0 atm) in the 4.4 SDK but it is still in development.

**Comment by rowest** [comment]
```
    compile 'com.swrve.sdk.android:swrve:4.1.0' 
    compile 'com.android.support:appcompat-v7:23.1.0'
    compile 'com.android.support:recyclerview-v7:23.1.0' 
    compile 'com.android.support:support-v4:23.1.0'
    compile 'com.android.support:design:23.1.0'
```

This is a part of my dependencies. I can't change them to 23.3.0 cause of some bugs with recyclerview. But I can't use 23.1.0 version anymore cause of your dynamic dependency com.android.support:appcompat-v7:23.+, gradle automaticly updating my appcompat libs to 23.4.0

**Comment by Sergio-Mira** [comment]
There is a way to include our SDK and exclude certain dependencies that might help, lemme know!

```
compile ('com.swrve.sdk.android:swrve:4.1.0') {
   exclude group: 'com.android.support', module: 'support-v4'
   exclude group: 'com.android.support', module: 'support-v7'
}
```

then keep adding your dependencies as normal and it should make it use your v4 / v7 version all around

**Comment by rowest** [comment]
Unfortunately still getting `java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/internal/widget/TintManager;`
Dependencies graph same as before:

```
+--- com.swrve.sdk.android:swrve:4.1.0
|    +--- com.google.code.gson:gson:2.2.+ -> 2.6.2
|    \--- com.android.support:appcompat-v7:23.+ -> 23.4.0 (*)
+--- com.android.support:appcompat-v7:23.1.0 -> 23.4.0 (*)
```

**Comment by Sergio-Mira** [comment]
Made a mistake with the module name of the v7 lib, could you try:

```
compile ('com.swrve.sdk.android:swrve:4.1.0') {
   exclude group: 'com.android.support', module: 'support-v4'
   exclude group: 'com.android.support', module: 'appcompat-v7'
}
```

**Comment by rowest** [comment]
Now I'm getting another error related to missed support.v7. 
`Error:(9, 31) error: cannot find symbol class ContextThemeWrapper` in this line: 
`import android.support.v7.view.ContextThemeWrapper;`

My gradle dependencies:
```
    compile ('com.swrve.sdk.android:swrve:4.1.0') {
        exclude group: 'com.android.support', module: 'support-v4'
        exclude group: 'com.android.support', module: 'appcompat-v7'
    }
    compile 'com.android.support:appcompat-v7:23.1.0'
    compile 'com.android.support:recyclerview-v7:23.1.0' 
    compile 'com.android.support:support-v4:23.1.0'
    compile 'com.android.support:design:23.1.0'
```

**Comment by rowest** [comment]
Thanks a lot, working like a charm!

**Comment by Sergio-Mira** [comment]
@freesbe we are specifying the exact version we use in the upcoming 4.4 SDK, however, you can workaround it using exclude group for the time being. Did you manage to solve your issue?

**Comment by Sergio-Mira** [comment]
We are now specifying the version we use except the patch version. Apps can ignore the version we use using the exclude trick. Will close for now and review again if someone has more issues with it. Thanks again!
