### ISSUE TITLE
Feature Request: Enable/Disable push notifications while an app is running

### ISSUE THREAD

**Issue by calaldees** [Swrve/swrve-android-sdk#145]
As a user I want to be able to opt in/out of push notifications.

Currently the SwrveSDK does not allow this config to be changed easily.
### Example of Attempted Approach

Below is an example of one of our experiments to implement this functionality with the existing SwrveSDK. We intend to make multiple calls to `start` while an application is running, as the user can make changes to the app's settings/state.

```
    public void start(final boolean isPushNotificationsEnabled) {
        if (mSwrveConfig != null && mSwrveConfig.isPushEnabled() == isPushNotificationsEnabled) {
            return;
        }
        stop();
        mSwrveConfig = new SwrveConfig();
        mSwrveConfig.setSenderId(isPushNotificationsEnabled ? mSwrveSenderId : "");
        try {
            mSwrve = SwrveSDK.createInstance(
                    mContext,
                    Integer.parseInt(mContext.getString(R.string.SWRVE_ANALYTICS_APP_ID)),
                    mContext.getString(R.string.SWRVE_ANALYTICS_APP_KEY),
                    mSwrveConfig
            );
        } catch (IllegalArgumentException exp) {
            LOG.e("Could not init the Swrve SDK", exp);
            stop();
            return;
        }
        mSwrve.setPushNotificationListener(mPushNotificationListener);
        if (!isPushNotificationsEnabled) {
            unregisterGoogleCloudMessaging();
        }
        LOG.i("start isPushEnabled="+mSwrveConfig.isPushEnabled());
    }

    public void stop() {
        if (mSwrve != null) {
            mSwrve.shutdown();
        }
        mSwrve = null;
        mSwrveConfig = null;
    }

    private void unregisterGoogleCloudMessaging() {
        LOG.i("Attempting unregister of push notifications");
        new Thread(() -> {
            try {
                InstanceID.getInstance(mContext).deleteInstanceID();
            } catch (IOException ex) {
                LOG.w("Unable to unregister GoogleCloudMessaging");
            }
        }).start();
    }
```
### Attempted Approaches Commentary

The experimented approaches below do not exhibit the required behaviour:
1. Restarting Swrve by calling `.shutdown()` followed by another `.createInstance` with an empty push `SenderId` provided in the config.
   - The App still receives push notifications. Even if the app is force stopped, restarted and `.createInstance` is called with an empty SenderId. Once the app has registered with a non null SenderId once, it will always receive push notifications.
2. Modify the SwrveConfig object that was passed to `SwrveSDK.createInstance` by calling `swrveConfig.setSenderId("")` and additionally calling `.setPushNotificationListener(null)`.
   - This approach fails because the `Swrve.gcm` packages have no knowledge of the SwrveConfig object and create system notifications regardless of the details in this config object.
     Setting `PushNotificationListener` to null is not sufficient. The listener is a handler for when the user interacts with a notification. The notifications still arrive.
3. Disabling push notifications directly in Google messaging API with `InstanceID.getInstance(mContext).deleteInstanceID();`
   - This was an attempt at performing the inverse of the way Swrve registers the Google Cloud messaging
     https://github.com/Swrve/swrve-android-sdk/blob/595f4faf64b32809d36594f87924a852eb668125/SwrveSDK/src/google/java/com/swrve/sdk/Swrve.java#L164
   - This approach works, it ensures the user receives no further push notifications; but push notifications can now never be re-enabled unless the app is reinstalled/reset. This call does not seem to be a simple toggle. Either Googles services are now in a mode where it has been permanently unregistered or Swrve is not making an attempt to re-register a with GoogleMessaging based on some previously stored state.
### Requested Feature Behaviour
- If `swrveConfig.isPushEnabled()` returns `false` the system notifications are suppressed for the user.
  - Maybe `SwrveGcmHandler` could be sympathetic to the state of `swrveConfig.isPushEnabled()` before it displays a notification.
    https://github.com/Swrve/swrve-android-sdk/blob/595f4faf64b32809d36594f87924a852eb668125/SwrveSDK/src/google/java/com/swrve/sdk/gcm/SwrveGcmHandler.java
- Provide a method `enablePushNotifications(boolean enabled)` that prevents the system notifications from being visible that we can call.

---

Let me know if I’ve overlooked any existing tools/functionality to allow us to reliably toggle push notifications.

Your time and assistance would be greatly appreciated.

Thanks

**Comment by Sergio-Mira** [comment]
Hi @calaldees thanks for letting us know about your use case. We do have plans to be able to disable and remove the push registration but it might not get implemented in the next few releases.

Here is an approach that could work for you now:
Extend the `SwrveGcmIntentService` class, overwrite the method `mustShowNotification` to return false whenever that setting is false and replace the SwrveSDK implementation with your own in the AndroidManifest.xml

Let me know how it goes, will keep this issue open until we implement the feature directly in the SDK and let you know when it is out

**Comment by calaldees** [comment]
Many thanks for your prompt reply.

With your guidance we now have a working solution based on SharedPreferences.

```
public class SwrveGcmIntentService extends com.swrve.sdk.gcm.SwrveGcmIntentService {
    @Override
    public boolean mustShowNotification() {
        final boolean isPushNotificationEnabled = this.getSharedPreferences(this.getPackageName(), Context.MODE_MULTI_PROCESS).getBoolean(PreferencesUtils.PUSH_NOTIFICATIONS_PREF_KEY, true);
        return isPushNotificationEnabled ? super.mustShowNotification() : false;
    }
}
```

Superb! Thank you!

**Comment by dominicmarmionswrve** [comment]
See `SwrveNotificationConfig.Builder.notificationCustomFilter` for handling display of notifications while the app is running.
