### ISSUE TITLE
Swrve crash on Android N (NPC91K) Nexus 6 Swrve version: 4.2.0

### ISSUE THREAD

**Issue by aradomski** [Swrve/swrve-android-sdk#164]
**Crash log:**

> Unable to insert into local storage
>                                                                           java.lang.NullPointerException: Attempt to invoke virtual method 'void com.swrve.sdk.localstorage.MemoryCachedLocalStorage.addEvent(java.lang.String)' on a null object reference
>                                                                               at com.swrve.sdk.SwrveImp$QueueEventRunnable.run(SwrveImp.java:1388)
>                                                                               at com.swrve.sdk.SwrveRunnables$1.run(SwrveRunnables.java:18)
>                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
>                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
>                                                                               at java.lang.Thread.run(Thread.java:803)

**Execution code:**

>  SwrveConfig config = new SwrveConfig();
>        config.setSelectedStack(SwrveStack.EU);
>         config.setAndroidIdLoggingEnabled(BuildConfig.DEBUG);
>         config.setHideToolbar(false);
>         config.setDefaultBackgroundColor(messageBackgroundColor);
>         config.setSenderId(gcmSenderId);
>         swrve = (Swrve) SwrveSDK.createInstance(appController, swrveAppId, swrveApiKey, config);
>         SwrveSDK.userUpdate(swrveHashMap); //swrveHashMap contains 1 element
>         SwrveSDK.event("");

Works fine on any device with Android prior to N.

**Comment by Sergio-Mira** [comment]
Hi @aradomski, createInstance does not initialise the SDK, it just creates a shared instance to be init on the Activity's onCreate and used after that, from the Activity's context.

**Comment by aradomski** [comment]
So to fix this 

```
SwrveSDK.userUpdate(swrveHashMap); //swrveHashMap contains 1 element
SwrveSDK.event("");
```

should be send after 

`SwrveSDK.onCreate(activity);`?

**Comment by Sergio-Mira** [comment]
Yes, the reason behind it is that your application could be started but none activity triggered. We send data when the SDK is started to calculate session length etc but can't send data outside of a this session without affecting DAU/other KPIs.

**Comment by aradomski** [comment]
Fixed, thanks!
