### ISSUE TITLE
Incorrect configuration of SwrveSDKCommon AndroidManifest.

### ISSUE THREAD

**Issue by aradomski** [Swrve/swrve-android-sdk#167]
In application tag attributes   android:allowBackup, android:label forces users of this library to add tools:replace attribute in theirs manifest (tools:replace="android:allowBackup,android:label"). If app contains many dependencies it forces to add this line in multiple places, which is not a great idea.
Link to file:
https://github.com/Swrve/swrve-android-sdk/blob/265c6c75c3718b1c2cff424c291fb599500e77de/SwrveSDKCommon/src/main/AndroidManifest.xml

android:supportsRtl="true" - may also cause the problem, but I haven't check it.

**Comment by dominicmarmionswrve** [comment]
Thanks @aradomski. This is a known issue and we'll resolve it in the next release which is due in next couple of weeks. Thanks for reporting.

**Comment by Sergio-Mira** [comment]
This has been released as part of 4.4.0, thanks for the heads up!
