### ISSUE TITLE
Provide official API to change 'userId' value at runtime

### ISSUE THREAD

**Issue by silin** [Swrve/swrve-android-sdk#170]
May be I missed something, but now there is no official way to change 'userId' after Swrve is initialized.
But in our app, for example, user can login with different accounts and all of them have different user identifiers. And that is strange that we have no possibility to change `userId` at runtime, because in our case when user changes his account, old `userId` becomes invalid.

Actually, we have two workarounds how to solve it, but both of them rely on some internals of Swrve sdk and should be verified on every library update.

So is it possible to add corresponding API for changing `userId`?

**Comment by Sergio-Mira** [comment]
Hi @silin we might have this in a foreseeable future, however our SDKs were not designed with this in mind and it will take a fair amount of time to implement right due to event data in transit / in storage that still needs to be sent/saved when changing user id, cached content, data migration and the effect it has on push notifications (even if the user changes, the push token doesn't).
Will keep you posted!

**Comment by kkucherenkov** [comment]
@silin Hi! Could you please provide some additional information about workarounds for userId changing? I have very similar issue in my app: User can login in different accounts with different user identifiers.

**Comment by silin** [comment]
@kkucherenkov we have following workarounds in our projects:
1) we always reinstantiate `SwrveSDK` instance with new `userId`. 
So far so good. Used on projects with tracking and in-app camapaigns. No major issues noticed for now
2) Most of SwrveSDK is `protected`. There are pros and cons of this. One of pros is
that we can override some methods that change `userId`. Used only on projects
without in-apps.

**Comment by silin** [comment]
Are there any news about supporting changing user id ([other than declined pull request with sample](https://github.com/Swrve/swrve-android-sdk/pull/261)). We still have to use hacks to change it in runtime, because if user logs in with different credentials in app, we have to apply different marketing campaigns and track event differently. 

Just interesting: why BTW it is not supported from the beggining (technical issues or by design)?

**Comment by oisin** [comment]
Hi @silin, yes we are planning to provide an official API to do permit this. It wasn't supported from the beginning as we didn't have anyone looking for the feature at the time, but the way the API worked, it was *possible* to change the User Id at runtime. We deliberately stopped that approach in v4.x, as it could cause wrong data attribution on the server side -- user X campaign data could instead be attributed to user Y.  We're building in constraints to ensure that the data is correctly attributed before shipping the feature.
