### ISSUE TITLE
Swrve not working correctly with agressive proguard

### ISSUE THREAD

**Issue by silin** [Swrve/swrve-android-sdk#200]
If client app uses proguard, it can obfuscate fields in Swrve model clasess that is used in JSON parsing. Because of this obfuscation, such fields in model classes are not parsed by GSON. That can cause a lot of issues in different places, in our cases in-app messages did not work because `Trigger` models were not parsed

**Comment by silin** [comment]
Fix for the issue: #199

**Comment by Sergio-Mira** [comment]
Thanks again @silin changes to work with aggressive pro guard configurations were released with 4.5. Let us know how it goes and reopen if needed!
