### ISSUE TITLE
Swrve blocks UI thread

### ISSUE THREAD

**Issue by vovkab** [Swrve/swrve-android-sdk#25]
For some reasons if internet connection is really slow, all your UI will be slow as well.
Any chance you guys can fix it?

**Comment by Sergio-Mira** [comment]
Thanks @vovkab for bringing this up. All the work is done in a background threads and it should not block the UI. However, the early start of the SDK does block the UI as we load the previous cache so you have the user resources and in-app messages ready after calling init.
We are adding a flag on the upcoming version 3.3.1 that will let you choose wether you want to wait on this cache to be loaded or not.

Some quick questions:
- Are you seeing this only at initialisation?
- What features are you using in the SDK: user resources, in-app messages, push? 
- Are you using user resources asynchronously? 
- Can you give us some guidance on how to reproduce it?

**Comment by Sergio-Mira** [comment]
Android 3.3.1 is out with the flag to let you choose if you want to wait for the cache to be loaded on initialisation:
config.setLoadCachedCampaignsAndResourcesOnUIThread(false);

**Comment by vovkab** [comment]
Tried new 3.3.1 looks like issue is gone.

**Comment by Sergio-Mira** [comment]
Thanks for letting us know!
