### ISSUE TITLE
Swrve session started callback

### ISSUE THREAD

**Issue by andreaboi83** [Swrve/swrve-android-sdk#256]
Is it possible to have a callback on Swrve session? I need to set some user properties as soon as the sdk is up and running and the session is fully started. The only callback I have found is about resources, but i didn't found nothing for the session.

**Comment by Sergio-Mira** [comment]
The session is started the first time an Activity calls our SDK's onCreate. If you queue the user update in your main activity's onCreate then you are sure to have the SDK ready.

**Comment by Sergio-Mira** [comment]
Please reopen this issue if you still have questions about when the SDK is started etc.
