### ISSUE TITLE
Gradle failing to fetch Swrve artifacts 

### ISSUE THREAD

**Issue by ghost** [Swrve/swrve-android-sdk#263]
Seems like a server / hosting issue; occurs intermittently on identical builds, unsure why the resources are sometimes still available.

- `Caused by: org.gradle.internal.resolve.ArtifactResolveException: Could not determine artifacts for com.swrve.sdk.android:swrve-google:4.5.0`
- `Caused by: org.gradle.api.resources.ResourceException: Could not get resource 'http://dl.bintray.com/swrve-inc/android/com/swrve/sdk/android/swrve-google/4.5.0/swrve-google-4.5.0.aar'.`
- `Caused by: org.gradle.api.UncheckedIOException: Could not HEAD 'http://dl.bintray.com/swrve-inc/android/com/swrve/sdk/android/swrve-google/4.5.0/swrve-google-4.5.0.aar'. Received status code 401 from server: Unauthorized`

Full stacktrace on PasteBin: [https://pastebin.com/RQUaJWL2](https://pastebin.com/RQUaJWL2)

Let me know if I can provide any additional info!

Edit: Yes, 4.5.0 is old, which I realized as a side effect of tracking this issue down.  Updated to 4.9.0, still having issues.

**Comment by dominicmarmionswrve** [comment]
Thanks for letting us know @AerinDeluca 
It seems like bintray were having issues on the 23rd May which would explain this. See http://status.bintray.com/
> May 23, 2017
> Download issues
> Resolved - This incident has been resolved. 
> May 23, 15:16 UTC
> Investigating - We are experiencing intermittent download issues. We are currently investigating and will update as soon as the issue is resolved. 
> May 23, 09:14 UTC

Sidenote: Is there a reason to force a redownload of these libraries on every build? It would be faster to let it download only once.

**Comment by ghost** [comment]
Thanks @dominicmarmionswrve !

Our build process does cache the artifacts acquired by gradle, but from what I understand gradle still HEADs all resources to see if they have changed to determine if it needs to download a new copy. I'm not entirely sure why, as I would expect a particular versioned library to always stay the same, and any changes to be released as a subsequent version, but that's just me. I'm not sure why getting a 401 when HEADing the library was forcing a gradle abort when we already had the library cached. Probably something I should look into on my end.

Thanks!
