### ISSUE TITLE
onResourcesUpdated() doesn't get triggered

### ISSUE THREAD

**Issue by 4gus71n** [Swrve/swrve-android-sdk#264]
Hi,

I'm using Swrve to do A/B testing over my Android App. In the Splash screen of my App if the BuildConfig.DEBUG is true I'm showing a dialog that allows the Developers/QA to choose different environments with different feature flags enabled or disabled. The problem that I'm having here is that the feature flags are only getting updated if I kill the App before open it. The flow is something like this:

The Developer/QA chooses the environment. Then I save the host url, the swrve app id, the swrve key, and some other environment-related info in the SharedPreferences.

Then I initialize the Swrve instance in my Application class like this:

```
Log.d("Test", String.format("Creating instance... AppId: %s AppKey: %s", swrveAppId, swrveApiKey));
ISwrve instance = SwrveSDK.createInstance(application, swrveAppId, swrveApiKey);
instance.setResourcesListener(this);
```

And once the `onResourcesUpdated()` callback gets triggered, I update some other values in the SharedPreferences that I'm going to use later in the App to display different UI flows.

The problem here is that no matter what the `onResourcesUpdated()` is only getting called if I killed the App previously. If I have the App open, and I re open it again the `onResourcesUpdated()` doesn't get called.

I tried hooking the `SwrveSDK.onCreate(this);` in the `onResume()` because I though that It was that method the one that was triggering the `onResourcesUpdated()`.

I tried deleting the cache file if it wasn't null. I tried setting different names for the database of each environment. But I cannot get the `onResourcesUpdated()` method called unless I kill the App and I open it again.

My question is; Is there any way to force the `onResourcesUpdated()` method to be called again?

**Comment by dominicmarmionswrve** [comment]
Hi @4gus71n, 

are you able to show your dialog from the Application onCreate method? I wouldn't have thought thats possible. The Application needs to be fully created first before any splash screen can be shown.

Swrve currently doesn't support switching appId's like this and hence the singleton design when SwrveSDK.createInstance is called. If you remain on the same environment, or skip the dialog code by using BuildConfig.RELEASE, does onResourcesUpdated get called each time user resources are updated?

**Comment by 4gus71n** [comment]
No, the dialog is being shown in the Activity, once the Developer/QA selects an environment I call `MyApplication.getInstance().initializeSwrve(appId, appKey);` which internally calls the `SwrveSDK.createInstance()` and `SwrveSDK.setResourceListener()` methods.

So basically an example of this issue is:
1) QA opens the App, see the environment dialog, selects the Development environment
2) `initializeSwrve()` method gets call, the `onResourcesUpdated()` callback gets triggered, we show the Development environment with all the feature flags and UI flows from the Development environment.
3) QA opens the App again, see the environment dialog, selects the QA environment.
4) `initializeSwrve()` method gets call, but the `onResourcesUpdated()` callback **never** gets triggered. Therefore, outdated feature flags are going to be shown.
5) Kill the App, open it again, now It will work properly.

The issue here is that unless I kill the App from the context menu and I open it again, the `onResourcesUpdated()` callback doesn't get call. Maybe it has something to do with the `SwrveSDK` singleton? Is there some workaround to bypass this?

**Comment by dominicmarmionswrve** [comment]
Yes, exactly. Because of the singleton, you can't switch environments like this. It isn't supported by Swrve. If you have push integrated, this will also be broken because you're not creating the instance from the Application onCreate method as per docs.

I'd suggest using flavors via build.gradle if you want different versions of your app for different environments.

Ultimately, switching environments isn't supported right now. However, we'll consider providing this sort of flexibility for version 5.0 which will be in the upcoming months.
