### ISSUE TITLE
Swrve rich notification doesn't work on obfuscated builds

### ISSUE THREAD

**Issue by filipkowicz** [Swrve/swrve-android-sdk#267]
obfuscated builds remove classes needed by gson to parse rich notification payloads. That results in fallback to simple text notification or crash on some devices.

**Comment by filipkowicz** [comment]
PR with fix #266

**Comment by Sergio-Mira** [comment]
Thanks @filipkowicz we'll add those in the next release.

**Comment by KevBrodigan** [comment]
Fixed in release-4_11_3
