### ISSUE TITLE
[Question] Disabling SDK for debug builds

### ISSUE THREAD

**Issue by arazabishov** [Swrve/swrve-android-sdk#268]
Is there currently a way to completely disable SDK for the debug builds? For instance, this is possible to do with Crashlytics by supplying `disable` flag when constructing an instance.

**Comment by Sergio-Mira** [comment]
At the moment it is not possible to do this but we'll look into adding it into an upcoming release

**Comment by dominicmarmionswrve** [comment]
Closing this as we've have no plans to do it. If its still a desired feature then please contact your CSM to discuss it further.
