### ISSUE TITLE
Gson version is not specified

### ISSUE THREAD

**Issue by dawidhyzy** [Swrve/swrve-android-sdk#269]
Currently + is used in Gson version number which is incorrect and slows down build process.

https://github.com/Swrve/swrve-android-sdk/blob/release-4_11_3/SwrveSDK/build.gradle#L36

**Comment by Sergio-Mira** [comment]
We'll set a hard dependency when we upgrade to the latest Gson in an upcoming release

**Comment by Sergio-Mira** [comment]
This was resolved some releases ago, at the time of writing we are using 2.8.5
