### ISSUE TITLE
`setSenderId` method missing for `SwrveConfig`

### ISSUE THREAD

**Issue by khat33b** [Swrve/swrve-android-sdk#272]
In the examples for push notifications, the sender id of Firebase is set in `SwrveConfig` using the method `setSenderId`. This method is missing in version `5.1.1`. 

My code is:
```
SwrveConfig config = new SwrveConfig();
config.setSenderId(R.string.swrve_sender_id);
        SwrveSDK.createInstance(application, 
                application.getResources().getInteger(R.integer.swrve_app_id),
                application.getString(R.string.swrve_api_key), config);
```

How do I set the sender id?

**Comment by Sergio-Mira** [comment]
Hi @khat33b that looks like an error in our snippet. Firebase doesn't need a sender id as everything is setup by the google-services.json. We'll fix the snippet today. Cheers!

**Comment by Sergio-Mira** [comment]
I can't find that in any snippet nor sample. Where did you see setSenderId? Was it maybe in a GCM section? Thanks!

**Comment by khat33b** [comment]
@Sergio-Mira https://github.com/Swrve/swrve-android-sdk/blob/release-5_1_1/samples/AdvancedPushNotifications/src/main/java/com/swrve/sdk/sample/SampleApplication.java

Ah yes, that sample still uses GCM. It looks like only the MultipleFCMProviders project uses FCM.
