### ISSUE TITLE
How to use the sdk with eclipse 

### ISSUE THREAD

**Issue by vinaybisht** [Swrve/swrve-android-sdk#274]
I am trying to integrate the sdk in eclipse. Is it possible to integrate it ??

**Comment by Sergio-Mira** [comment]
Hi @vinaybisht we haven't had anyone integrate it with Eclipse in a long while. I think your best bet would be to use the 3 aars (common, conversations and the flavour of the SDK you want) and use this maven plugin http://simpligility.github.io/android-maven-plugin/ which supports aars

Another alternative would be to include the SDK by source and pull all the dependencies from Maven.
