### ISSUE TITLE
Error sending events to Swrve. responseCode: 403

### ISSUE THREAD

**Issue by vinaybisht** [Swrve/swrve-android-sdk#275]
While integrating Swrve. I am getting following error. I am not aware why i am getting this error

Please help me to resolve this.

Thanks

**Comment by Sergio-Mira** [comment]
Hi @vinaybisht it sounds like the api_key you are using is incorrect. If you are still hitting issues please get in contact with our Customer Support here: https://support.swrve.com/hc/en-us
