### ISSUE TITLE
Timber exposed

### ISSUE THREAD

**Issue by dawidhyzy** [Swrve/swrve-android-sdk#277]
Using `api` you expose old Timber dependency.
https://github.com/Swrve/swrve-android-sdk/blob/release-5_2/SwrveSDKCommon/build.gradle#L25

Use `implementation` instead.

**Comment by Sergio-Mira** [comment]
Hi @dawidhyzy thanks for raising the issue, we'll change it in the next release!

**Comment by dominicmarmionswrve** [comment]
Thanks @dawidhyzy, this is now fixed in the latest sdk.
