### ISSUE TITLE
Starting SwrveGcmIntentService failing in Oreo

### ISSUE THREAD

**Issue by dayerdl** [Swrve/swrve-android-sdk#278]
Hello,

We are receving a crash on devices Oreo when starting this service in the background. We cant extend JobIntentService as SwrveGcmIntentService is inside the SDK. So our class CustomSwrveGcmIntentService depend on that.

```    
private void showSwrveNotification(Context context, Intent intent) {
        ComponentName comp = new ComponentName(context.getPackageName(), CustomSwrveGcmIntentService.class.getName());
        intent.setComponent(comp);
        context.startService(intent);
    }
```

**Comment by Sergio-Mira** [comment]
Hi @dayerdl if you have multiple GCM providers you have to update it to support Android O as shown in our sample: https://github.com/Swrve/swrve-android-sdk/tree/release-5_2/samples/MultipleGCMProviders

**Comment by dayerdl** [comment]
@Sergio-Mira we are extending SwrveGcmIntentService and adding some customization. I cant see an example which is extending this class.

**Comment by Sergio-Mira** [comment]
Could you give us a bit more information on what your setup is and what you are trying to achieve?

If you extend the intent service and it is started by the GCM libs you shouldn't need to do anything special for Android O, GCM libs will do it for you. You just need to replace the service with your custom one in the AndroidManifest.xml.
The example AdvancedPushNotifications has an example of an extended SwrveGcmIntentService

**Comment by dayerdl** [comment]
Hi Sergio,

We have a common receiver for GCM notifications which extends GCMReceiver and is declared in the manifest.xml. Then when we receive we read intent.getExtras() and if the value is 2 we handle it like a SwreNotification and start the CustomService like:

```
    private void showSwrveNotification(Context context, Intent intent) {
        ComponentName comp = new ComponentName(context.getPackageName(), CustomSwrveGcmIntentService.class.getName());
        intent.setComponent(comp);
        context.startService(intent);
    }
```

Android O does not allow us to call startService, and we cant transform CustomSwrveGcmIntentService and extend JobIntentService for example. Any idea?

**Comment by Sergio-Mira** [comment]
Hi @dayerdl 

You'll have to add a special case for Android O where you start a JobService where you call the method `onMessageReceived` of `SwrveGcmIntentService`. We'll soon be adding a sample project showing how to do this and we'll be looking into simplifying all this in the next 6.0 SDK series.

Let me know how it goes.

**Comment by Sergio-Mira** [comment]
Sample project was added a couple of releases back to show how to do this
