### ISSUE TITLE
How to disable/enable push notifications while app is running

### ISSUE THREAD

**Issue by mccartneym** [Swrve/swrve-android-sdk#279]
What is the current best way to enable/disable push notifications while the app is running?

There was an answer to this in #145 (March 2016) but it looks like that has changed.

**Comment by dominicmarmionswrve** [comment]
Hi @mccartneym, as of version 6.0.1 you can provide a `SwrveNotificationCustomFilter` to your `SwrveNotificationConfig`, where you have final control over displaying a notification. Return null from the `filterNotification` method to disable showing the notification based on your own internal logic.

https://github.com/Swrve/swrve-android-sdk/blob/release-6_0_1/SwrveSDKCommon/src/main/java/com/swrve/sdk/SwrveNotificationCustomFilter.java#L18

Any questions let us know.

**Comment by mccartneym** [comment]
Hi @dominicmarmionswrve,
Thanks very much for that!
