### ISSUE TITLE
In-app messages doesn't show up

### ISSUE THREAD

**Issue by vovkab** [Swrve/swrve-android-sdk#28]
Dialog is flashes for less than a second but didn't stay on screen.

So what is happening is you show dialog from the onCreate of new activity and remove it in onDestroy from old activity.

Since you remove dialog in onDestroy, when you back from activity, onDestroy will be called later than new activity onCreate.

Easiest way to reproduce, check "Don't keep activities" in developer settings

**Comment by Sergio-Mira** [comment]
Thanks @vovkab for letting us know. Does the case you present involve two different Activities (one calling onCreate and the old one calling onDestroy)?

**Comment by vovkab** [comment]
Yes, we want use swrve in every screen.

**Comment by Sergio-Mira** [comment]
We managed to reproduce the error and fix it. We are targeting the change for the upcoming 3.4 SDK:
https://github.com/Swrve/swrve-android-sdk/pull/33

Thanks again!

**Comment by vovkab** [comment]
@Sergio-Mira btw, why you decided to use dialog instead of just creating a new activity instead?

**Comment by vovkab** [comment]
Looks like fixed, but now there is few more new issues with 3.4rc
