### ISSUE TITLE
[Crash] when get a new push notification on the build type which enabled ProGuard

### ISSUE THREAD

**Issue by patrickyin** [Swrve/swrve-android-sdk#280]
### Issue
The app build which enabled ProGuard is crashed when a new Swrve push notification comes.

### Cause
After obfuscation, the GSON model class's name or properties' name has been changed, but GSON uses property reflection to map the JSON object to model class. So when the new push comes, the GSON couldn't deserialize the response.

### Solution
Avoid the push notification related models are obfuscated by adding an additional ProGuard rule to the SDK

**Comment by dominicmarmionswrve** [comment]
@patrickyin We'll add a change to address this in our 6.1 release which should be public in next few weeks. Thanks for logging the issue.

**Comment by dominicmarmionswrve** [comment]
@patrickyin a fix for this issue is now part of release 6.1 

I'll close this issue in a couple of days if you've no further comments. Thanks again for reporting it!

**Comment by patrickyin** [comment]
Thanks @dominicmarmionswrve
