### ISSUE TITLE
Timber logging

### ISSUE THREAD

**Issue by Dimezis** [Swrve/swrve-android-sdk#284]
Hi,
Could you please consider some other way of logging, or maybe just delegate Timber initialization to the app, because right now if the app plants its own debug tree, all logging events are duplicated:

https://github.com/JakeWharton/timber/issues/121

**Comment by dominicmarmionswrve** [comment]
Hi @Dimezis, thanks for bringing this to our attention. We'll fix this in our next release which is in next few weeks.

**Comment by dominicmarmionswrve** [comment]
Hi @Dimezis, we've released SwrveSDK 6.1 today which has a new api to allow you to use your own Timber Tree and switch ours off. The api is called `SwrveLogger.useCustomLogger` and more details can be found [here](https://docs.swrve.com/faqs/sdk-integration/disable-sdk-device-logging/).

I'll close this issue in a couple of days if you've no further comments. Thanks again for reporting it!
