### ISSUE TITLE
[Security] Static Scan Issues

### ISSUE THREAD

**Issue by KumariAnjuThakur** [Swrve/swrve-android-sdk#287]
Hi
We are using Version 5.2.0 are there are  following issues faced in static security scan :
**Vera Code Issues:**
1. Improper Output Neutralization for Logs
2. Insufficient Entropy CWE ID 331
3.  Use of a Broken or Risky Cryptographic Algorithm CWE ID 327
4. Information Exposure Through Sent Data CWE ID 201
**MobSF Platform Scan issues:** 
1. MD5 is a weak hash known to have hash collisions
2. App Uses SQLite Database and executes the raw SQL query. Untrusted user input in raw SQL queries can cause SQL Injection. Also, sensitive information should be encrypted and written to the database. 

We are looking forward to your support.

Thanks

**Comment by davidbreenwex** [comment]
Hi @KumariAnjuThakur,

The MD5 hash is used to create a session token and is not used to transfer any sensitive information.

I'd like to get some clarification on some of the other points. Its probably best to close this issue on github and open a support ticket instead. 
Please send an email to support@swrve.com for further assistance.

Thanks, 
David
