### ISSUE TITLE
Swrve not supporting android support library version 28.0.0

### ISSUE THREAD

**Issue by HarmeetKaur94** [Swrve/swrve-android-sdk#288]
Hi,
We are using Version 5.2.0 in our project, On upgrading android support libraries from 27.1.1 to 28.0.0. We are getting **failure in linking references** in some of the files. The files in which we are getting error are listed below:

- **swrve_rating_bar.xml** at all the items
- **values-v28.xml** at Base.V28.Theme.AppCompat.Light
- **values.xml** at ForegroundLinearLayout, MaterialButton

We are looking forward to your support.
Thanks

**Comment by davidbreenwex** [comment]
Hi @HarmeetKaur94,

We upgraded to version 28.0.0 in version 6.1 of the SDK. 
The easiest way to solve your conflict would be to upgrade to the latest version.

If you need any further support on this issue I recommend contacting the Swrve support team on:
support@swrve.com
This way it will enter our support queue and be dealt with more quickly.

Thanks, 
David
