### ISSUE TITLE
In-App messages doesn't show up immediately after firing an event.

### ISSUE THREAD

**Issue by vovkab** [Swrve/swrve-android-sdk#29]
Maybe we got this wrong. But if we setup in-app message for an event, we expect this event to be shown right after we open this screen (fire an actuall event).

What happens right now is you show(sometimes) message only for new activity. So let's say we have in-app message for "home" event. It will never show message when we actually open home, but only when we go somewhere else like "home" -> "browse" now we are showing message. Which is not something we would expect.

**Comment by Sergio-Mira** [comment]
There are several factors that could be preventing the message from appearing:
- Is this event launched right after init / initOrBind? The campaign data and images might still be loading asynchronously.
- Have you checked the message rules? We have rules to stop messages from appearing too many times, too soon after launch and too close to each other. There are also similar global rules for your app under the In-app Settings.
- Do you have all the hooks in your activities: onCreate, onResume, onPause, onDestroy?

Messages are triggered only when the configured event is triggered, no other event can trigger them. Could you send more information to support@swrve.com with a link to your campaign and app in our dashboard?

Thanks and have a nice weekend!

**Comment by vovkab** [comment]
We have base activity:
onCreate() { swrve.initOrBind() }
onPause() { swrve.onPause() }
onResume() { swrve.onResume() }
onDestroy() {swrve.onDestroy() }
onLowMemory() { swrve.onLowMemory() }

And then we call swrve.event() when we want to send something.

That is all we have. 
I sent camping id to support email.

**Comment by Sergio-Mira** [comment]
Closing for now, let us know if you are still having issues!
