### ISSUE TITLE
Update firebase-messaging dependency to 19.0.*

### ISSUE THREAD

**Issue by nimeacuerdo** [Swrve/swrve-android-sdk#291]
Hi,

we are currently including swrve-firebase dependency in our project and would like to migrate **firebase-messaging** to, at least, 19.0.* but it turns out that **swrve-firebase** depends on **firebase-messaging** 17.4.0 which in turn has a fixed dependency with **firebase-iid** 17.1.0 (which conflicts with the newer **firebase-iid** 19.0.0).

Do you plan to update your dependency in the short term?

Thanks

**Comment by davidbreenwex** [comment]
Hi @nimeacuerdo,

We are currently discussing internally how best to approach this as upgrading will require we drop support for Android versions 14 & 15. I'll update you as soon as we have decided how and when to upgrade. 

Best, 
David

**Comment by nimeacuerdo** [comment]
Thanks for the update, @davidbreenwex!

**Comment by nimeacuerdo** [comment]
Any target release for this?

Thanks

**Comment by davidbreenwex** [comment]
Hi @nimeacuerdo 

This will be included in the next major version release 7.0 which is scheduled for the end of next quarter.
I'll update you when the release goes out. 

Thanks,
David

**Comment by gmerinojimenez** [comment]
Hi @davidbreenwex, thanks for your answer.

Then you're forcing to all users of Swrve to be stuck in a Firebase version that is almost a year old. Considering the importance of Firebase libraries, aren't you considering an earlier update from your side regarding this?

Thanks in advance.

**Comment by davidbreenwex** [comment]
Hi @nimeacuerdo,

Thank you for your patience. 
Work on this has started on this now and will be included in our next SDK release. 
As it is a major SDK release we will be including some other features with breaking changes. 
I don't have a concrete date for release but I will update you as soon as I know for sure. 

Best, 
David

**Comment by davidbreenwex** [comment]
Hi @nimeacuerdo and @gmerinojimenez,

We have now released a new version of the Swrve Android SDK:
https://docs.swrve.com/release-notes/sdk-release-notes/android-sdk-release-notes/#Release_70

In this release we updated firebase-messaging from 17.4.0 to 20.1.0.

Let me know if you have any further questions on this. 

Best, 
David
