### ISSUE TITLE
Migrate from JCenter

### ISSUE THREAD

**Issue by dcampogiani** [Swrve/swrve-android-sdk#298]
Source: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by Sergio-Mira** [comment]
Hi @dcampogiani we are actively looking into this, will update this issue with information on how/when we are moving.
JCenter can still be used to pull dependencies throughout 2021 so should have no impact for now.

**Comment by dcampogiani** [comment]
@Sergio-Mira thanks for the reply.

My concern is mainly about updates. From my understanding from March 31st, 2021 no more submissions will be accepted to JCenter.

**Comment by Sergio-Mira** [comment]
We'll be releasing some changes this month to JCenter and then move to publish to Maven Central or similar, then continue shipping updates.

**Comment by dominicmarmionswrve** [comment]
@dcampogiani thank you for reporting the issue. Our existing releases have now migrated to JCenter and Maven Central. And our future ones will go there too. We'll update our docs soon also.
