### ISSUE TITLE
SDK docs?

### ISSUE THREAD

**Issue by Bradleycorn** [Swrve/swrve-android-sdk#299]
Is there any documentation of the api's exposed by this SDK? I can't seem to find anything anywhere?
Note: I'm not talking about an integration guide (which I have found on the swrve developer portal), but documenation of the public API (classes, methods, and arguments) that this sdk exposes?

**Comment by Sergio-Mira** [comment]
Hi @Bradleycorn the SDK has Javadoc  annotations and it should show on the IDE. We don't have at the moment any other online documentation.
