### ISSUE TITLE
SwrveSDK.getResourceManager() is returning null

### ISSUE THREAD

**Issue by indieboyalex** [Swrve/swrve-android-sdk#300]
We are seeing a few instances in Crashlytics where calls to `SwrveSDK.getResourceManager()` are returning null.

We can see that Swrve has been initialised - no Runtime exception from the internal `checkInstanceCreated()` call is being thrown.  Is there any reason why this would be returning null?

**Comment by dominicmarmionswrve** [comment]
Hi @iNdieboyjeff, thanks for reporting the issue. Could you provide the stacktrace please?

**Comment by dominicmarmionswrve** [comment]
The init of the ResourceManager is dependent on foreground activity. Is it possible you are using the ResourceManager from a background worker where the app hasn't actually gone into the foreground?

Also, have you changed the default value of the `isLoadCachedCampaignsAndResourcesOnUIThread` SwrveConfig setting? If  this is false then its possible ResourceManager did not get initialised yet.

**Comment by dominicmarmionswrve** [comment]
@iNdieboyjeff Is there any update on this? We'll close the issue if there's no further update.

**Comment by dominicmarmionswrve** [comment]
Thanks :)

**Comment by indieboyalex** [comment]
It looks like someone had set isLoadCachedCampaignsAndResourcesOnUIThread to false, though we have also migrated to other functionality which means we don’t need to use the resource manager directly now anyway.

**Comment by dominicmarmionswrve** [comment]
Ah right, that makes sense. Thanks again for quick reply!!
