### ISSUE TITLE
Android 12 - Target S/31 Support

### ISSUE THREAD

**Issue by alexpopa95** [Swrve/swrve-android-sdk#302]
With the latest version `8.0.0` the method `SwrvePushManagerImp.processNotification(...)` throws an `IllegalArgumentException` on app **targeting API 31**:
```
java.lang.IllegalArgumentException: com.xxx.xxx: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
```

The issue seems to be connected to `androidx.work:work-runtime` dependency that should be updated to `2.7.0`.

Release Notes: [HERE](https://developer.android.com/jetpack/androidx/releases/work#2.7.0-alpha02)
Google Issue: [HERE](https://issuetracker.google.com/issues/180884673)

 Is there any timeline on when the fix will be released?

**Comment by dominicmarmionswrve** [comment]
Hi @alexpopa95, thank you for logging the issue. We're currently working on a new release to address all the issues with targeting api level 31. The new release will be using work-runtime 2.7.0 and will address the other behavioural changes outlined [here](https://developer.android.com/about/versions/12/behavior-changes-12). Hopefully a new version will be published in the next few weeks. If there's any delay we'll keep you updated here.

**Comment by alexpopa95** [comment]
Thank you for the update @dominicmarmionswrve

**Comment by dominicmarmionswrve** [comment]
@alexpopa95 We've just published an update to the sdk to support Android 12. This is a major version update and requires your app to have a `compileSdkVersion` of 31. The update should resolve the issue logged here so I'll close this issue now. Thanks for getting in touch!
