### ISSUE TITLE
Listerner not working for get compaign data 

### ISSUE THREAD

**Issue by tayyabsys** [Swrve/swrve-android-sdk#304]
hi bro SwrSDK show compain data in log but not show in listerner 
i have used this piece of code for getting data kindly guide me as soon as possible 
   val config = SwrveConfig();
        // To use the EU stack, include this in your config.
        config.selectedStack = SwrveStack.EU
        SwrveSDK.createInstance(application,1223 , "<apiKey>", config);

        var embeddedMessageListener =
            SwrveEmbeddedMessageListener { context, message, personalizationProperties ->
                // perform your own message rendering
                Timber.d("MyCash:  ${message?.data.toString()}")
                Timber.d("MyCash:  ${personalizationProperties.values}")
                personalizationProperties.values
                System.out.println(message.getData()) //getData is where your JSON resides
            }
        var embeddedMessageConfig = SwrveEmbeddedMessageConfig.Builder()
            .embeddedMessageListener(embeddedMessageListener)
            .build()
        config.embeddedMessageConfig=embeddedMessageConfig

**Comment by davidbreenwex** [comment]
Hi @tayyabsys 

Please open a support ticket by emailing support@swrve.com if you still require help with this. 

Thanks, 
David
