### ISSUE TITLE
Long load time when Cellular Network

### ISSUE THREAD

**Issue by forfiter9** [Swrve/swrve-android-sdk#305]
We spotted a problem on our apps with the SDK. Some communications part with SWRVe is taking much more time (few minutes) on cellular network (on wifi connection everything is working totally fine) . Do you have maybe any idea or tips where we can search a source problem for it? When we are disabling all communication connected with SWRVe then app is working totally fine on both cellular and wifi.

**Comment by davidbreenwex** [comment]
Hi @forfiter9 

Please open a support ticket at support@swrve.com if you still need help with this. 

Thanks, 
David
