### ISSUE TITLE
Null (\N) Custom Properties Data against many swrve_data_id in Swrve Database CSV

### ISSUE THREAD

**Issue by ahmednawaz22** [Swrve/swrve-android-sdk#306]
Hi there,
Greetings!

I've just downloaded Data Files of Custom User properties from SandBox and Production Environment, there are many anomalies in these downloaded CSV data files, as 40% of swrve_data_id has this "\N" value in all cells of the row. What is it "\N"? in some cases there are empty cells where the app sends an empty string and that is fine but this "\N" is strange. Is it referring to null data or something else?
For IOS app data, all cells related to OS and App version are filled with "\N" text.
We also perform debugging in QA devices and Custom User Properties are working fine, both on SandBox and Production.

Thanks,

**Comment by davidbreenwex** [comment]
Hi @ahmednawaz22 ,

Can you please log a support ticket for this issue by sending an email to support@swrve.com?
Its not likely related to the SDK. 

Thanks, 
David
