### ISSUE TITLE
In-App message fire for a wrong screen

### ISSUE THREAD

**Issue by vovkab** [Swrve/swrve-android-sdk#34]
Sdk version 3.4.0rc

1. I have screens A -> B,
2. Created in-app message A.enter
3. Sending event from A onCreate: swrve.event(A.enter)

Expected: when I open B, there should be no message from A
Actual: right now A message fire in B also

**Comment by Sergio-Mira** [comment]
Is this issue still happening?

**Comment by Sergio-Mira** [comment]
Let us know if this issue is still happening and we'll have a look, thanks!
